/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BuildingGridChart: typeof import('./src/components/BuildingGridChart.vue')['default']
    BuildingHeatChart: typeof import('./src/components/BuildingHeatChart.vue')['default']
    BuildingInformation: typeof import('./src/components/BuildingInformation.vue')['default']
    BuildingTreeChart: typeof import('./src/components/BuildingTreeChart.vue')['default']
    CategoricalSelect: typeof import('./src/components/CategoricalSelect.vue')['default']
    CoolingCenter: typeof import('./src/components/CoolingCenter.vue')['default']
    DisclaimerPopup: typeof import('./src/components/DisclaimerPopup.vue')['default']
    Filters: typeof import('./src/components/Filters.vue')['default']
    FloodBackgroundSyke: typeof import('./src/components/FloodBackgroundSyke.vue')['default']
    Geocoding: typeof import('./src/components/Geocoding.vue')['default']
    GridView: typeof import('./src/components/GridView.vue')['default']
    HeatHistogram: typeof import('./src/components/HeatHistogram.vue')['default']
    HeatHistogramHelsinki: typeof import('./src/components/HeatHistogramHelsinki.vue')['default']
    HSYAreaSelect: typeof import('./src/components/HSYAreaSelect.vue')['default']
    HSYBuildingHeatChart: typeof import('./src/components/HSYBuildingHeatChart.vue')['default']
    HSYScatterplot: typeof import('./src/components/HSYScatterplot.vue')['default']
    HSYWMS: typeof import('./src/components/HSYWMS.vue')['default']
    HSYYearSelect: typeof import('./src/components/HSYYearSelect.vue')['default']
    Layers: typeof import('./src/components/Layers.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    NDVIChart: typeof import('./src/components/NDVIChart.vue')['default']
    NearbyTreeArea: typeof import('./src/components/NearbyTreeArea.vue')['default']
    NumericalSelect: typeof import('./src/components/NumericalSelect.vue')['default']
    PieChart: typeof import('./src/components/PieChart.vue')['default']
    PopGridLegend: typeof import('./src/components/PopGridLegend.vue')['default']
    PostalCodeNDVI: typeof import('./src/components/PostalCodeNDVI.vue')['default']
    PostalCodeView: typeof import('./src/components/PostalCodeView.vue')['default']
    PrintBox: typeof import('./src/components/PrintBox.vue')['default']
    Scatterplot: typeof import('./src/components/Scatterplot.vue')['default']
    SocioEconomicsChart: typeof import('./src/components/SocioEconomicsChart.vue')['default']
    SocioEconomicsSelect: typeof import('./src/components/SocioEconomicsSelect.vue')['default']
    SosEco250mGrid: typeof import('./src/components/SosEco250mGrid.vue')['default']
    StatisticalGridOptions: typeof import('./src/components/StatisticalGridOptions.vue')['default']
    SurveyScatterPlot: typeof import('./src/components/SurveyScatterPlot.vue')['default']
    Timeline: typeof import('./src/components/Timeline.vue')['default']
    ViewMode: typeof import('./src/components/ViewMode.vue')['default']
    VulnerabilityChart: typeof import('./src/components/VulnerabilityChart.vue')['default']
  }
}
