version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev # Use the development Dockerfile
    volumes:
      - .:/usr/src/app # Mount the project directory inside the container
      - /usr/src/app/node_modules # Persist node_modules
    ports:
      - "5173:5173" # Expose the Vue app's port
    environment:
      - NODE_ENV=development
    command: npm run dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"