version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile # Use the production Dockerfile
    ports:
      - "80:80" # Nginx serves on port 80
    environment:
      - NODE_ENV=production
    # Additional environment variables can be added here if needed

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile # Make sure this points to your backend Dockerfile
    ports:
      - "3000:3000" # Expose the backend port
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"