version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile # Use the production Dockerfile
    ports:
      - "80:80" # Nginx serves on port 80
    environment:
      - NODE_ENV=production
    # Additional environment variables can be added here if needed

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"