apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: r4c
build:
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
  artifacts:
    - image: frontend
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: r4c
        chartPath: helm
        valuesFiles:
          - helm/values.yaml
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_frontend}}"
          image.tag: "{{.IMAGE_TAG_frontend}}@{{.IMAGE_DIGEST_frontend}}"
        setValues:
          # image.pullPolicy: "IfNotPresent"
