apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: r4c-cesium-viewer
build:
  local:
    useBuildkit: true
    concurrency: 0
  artifacts:
    - image: viewer
      context: .
      docker:
        dockerfile: Dockerfile
    - image: backend
      context: backend
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: r4c-cesium-viewer
        chartPath: helm
        valuesFiles:
          - helm/values.yaml
        version: 0.1.0
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_viewer}}"
          image.tag: "{{.IMAGE_TAG_viewer}}@{{.IMAGE_DIGEST_viewer}}"
          image2.repository: "{{.IMAGE_REPO_backend}}"
          image2.tag: "{{.IMAGE_TAG_backend}}@{{.IMAGE_DIGEST_backend}}"
        setValues:
          image.pullPolicy: "IfNotPresent"
          image2.pullPolicy: "IfNotPresent"
          vite.backend_url: "/backend"
