apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: r4c-cesium-viewer
build:
  local:
    push: false
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
  artifacts:
    - image: frontend
      context: .
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/serviceaccount.yaml
    - k8s/configmap.yaml
    - k8s/secrets.yaml
    - k8s/deployment.yaml
    - k8s/service.yaml
    - k8s/ingress.yaml
deploy:
  kubectl:
    hooks:
      before:
        - host:
            command:
              ["sh", "-c", "dotenvx run -- sh scripts/generate-secrets.sh"]
profiles:
  - name: local-with-services
    manifests:
      rawYaml:
        - k8s/serviceaccount.yaml
        - k8s/configmap.yaml
        - k8s/secrets.yaml
        - k8s/migration-secret.yaml
        - k8s/migration-job.yaml
        - k8s/deployment.yaml
        - k8s/service.yaml
        - k8s/ingress.yaml
        - k8s/pygeoapi-deployment.yaml
        # PostgreSQL with PostGIS (official postgis/postgis image)
        - k8s/postgresql-secret.yaml
        - k8s/postgresql-configmap.yaml
        - k8s/postgresql-headless-service.yaml
        - k8s/postgresql-service.yaml
        - k8s/postgresql-statefulset.yaml

  - name: migration-test
    manifests:
      rawYaml:
        # PostgreSQL with PostGIS (official postgis/postgis image)
        - k8s/postgresql-secret.yaml
        - k8s/postgresql-configmap.yaml
        - k8s/postgresql-headless-service.yaml
        - k8s/postgresql-service.yaml
        - k8s/postgresql-statefulset.yaml
    test:
      - image: amacneil/dbmate:v2.13.0
        custom:
          - command: "sh -c 'apk add --no-cache postgresql-client && /scripts/test_migration.sh'"
            timeoutSeconds: 600
            dependencies:
              paths:
                - "db/migrations/*.sql"
                - "scripts/test_migration.sh"
