apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: r4c-cesium-viewer
build:
  local:
    push: false
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
  artifacts:
    - image: frontend
      context: .
      docker:
        dockerfile: Dockerfile
      hooks:
        before:
          # Load .env if present, then generate secrets (script has sensible defaults)
          - command:
              [
                'sh',
                '-c',
                '[ -f .env ] && set -a && . ./.env && set +a; sh scripts/generate-secrets.sh',
              ]
            os: [darwin, linux]
          # Run lint before build to catch errors early
          - command: ['sh', '-c', 'bun run lint --silent || echo "Lint warnings found"']
            os: [darwin, linux]
    - image: dbmate-migrations
      context: db
      docker:
        dockerfile: Dockerfile
# Default: Full stack with all services (PostgreSQL, pygeoapi, frontend)
manifests:
  rawYaml:
    - k8s/namespace.yaml
    - k8s/serviceaccount.yaml
    - k8s/configmap.yaml
    - k8s/secrets.yaml
    - k8s/migration-secret.yaml
    - k8s/migration-job.yaml
    - k8s/deployment.yaml
    - k8s/service.yaml
    - k8s/ingress.yaml
    - k8s/pygeoapi-deployment.yaml
    # PostgreSQL with PostGIS (simple single-instance deployment)
    - k8s/postgresql-secret.yaml
    - k8s/postgresql-configmap.yaml
    - k8s/postgresql-pvc.yaml
    - k8s/postgresql-service.yaml
    - k8s/postgresql-deployment.yaml
deploy:
  kubeContext: orbstack
  kubectl: {}
  # Wait up to 180s for pods to be ready; tolerate init container restarts
  statusCheck: true
  statusCheckDeadlineSeconds: 180
  tolerateFailuresUntilDeadline: true
# Bind to localhost only for security
portForward:
  - resourceType: service
    resourceName: r4c-cesium-viewer
    port: 80
    localPort: 4173
    address: 127.0.0.1
profiles:
  # Services only (PostgreSQL, pygeoapi) - use with 'npm run dev' for frontend
  - name: services-only
    build:
      artifacts:
        - image: dbmate-migrations
          context: db
          docker:
            dockerfile: Dockerfile
    manifests:
      rawYaml:
        - k8s/namespace.yaml
        - k8s/serviceaccount.yaml
        - k8s/configmap.yaml
        - k8s/migration-secret.yaml
        - k8s/migration-job.yaml
        - k8s/pygeoapi-deployment.yaml
        - k8s/postgresql-secret.yaml
        - k8s/postgresql-configmap.yaml
        - k8s/postgresql-pvc.yaml
        - k8s/postgresql-service.yaml
        - k8s/postgresql-deployment.yaml
    deploy:
      kubeContext: orbstack
      kubectl: {}
    portForward:
      - resourceType: service
        resourceName: postgresql
        port: 5432
        localPort: 5434
        address: 127.0.0.1
      - resourceType: service
        resourceName: pygeoapi
        port: 80
        localPort: 5001
        address: 127.0.0.1

  # Frontend only - assumes services-only is already running
  # Use: skaffold run -p services-only && skaffold dev -p frontend-only
  - name: frontend-only
    build:
      artifacts:
        - image: frontend
          context: .
          docker:
            dockerfile: Dockerfile
          hooks:
            before:
              # Load .env if present, then generate secrets (script has sensible defaults)
              - command:
                  [
                    'sh',
                    '-c',
                    '[ -f .env ] && set -a && . ./.env && set +a; sh scripts/generate-secrets.sh',
                  ]
                os: [darwin, linux]
              - command: ['sh', '-c', 'bun run lint --silent || echo "Lint warnings found"']
                os: [darwin, linux]
    manifests:
      rawYaml:
        - k8s/namespace.yaml
        - k8s/serviceaccount.yaml
        - k8s/configmap.yaml
        - k8s/secrets.yaml
        - k8s/deployment.yaml
        - k8s/service.yaml
        - k8s/ingress.yaml
    deploy:
      kubeContext: orbstack
      kubectl: {}
      statusCheck: true
      statusCheckDeadlineSeconds: 120
      tolerateFailuresUntilDeadline: true
    portForward:
      - resourceType: service
        resourceName: r4c-cesium-viewer
        port: 80
        localPort: 4173
        address: 127.0.0.1

  - name: e2e-with-prod-data
    manifests:
      rawYaml:
        - k8s/serviceaccount.yaml
        - k8s/configmap.yaml
        - k8s/secrets.yaml
        - k8s/deployment.yaml
        - k8s/service.yaml
        - k8s/ingress.yaml
        - k8s/pygeoapi-deployment.yaml
        # PostgreSQL with PostGIS (simple single-instance deployment)
        - k8s/postgresql-secret.yaml
        - k8s/postgresql-configmap.yaml
        - k8s/postgresql-pvc.yaml
        - k8s/postgresql-service.yaml
        - k8s/postgresql-deployment.yaml
        # Database clone from GCS production dumps
        - k8s/db-clone-from-gcs-job.yaml

  - name: migration-test
    manifests:
      rawYaml:
        - k8s/namespace.yaml
        - k8s/migration-secret.yaml
        # PostgreSQL with PostGIS (simple single-instance deployment)
        - k8s/postgresql-secret.yaml
        - k8s/postgresql-configmap.yaml
        - k8s/postgresql-pvc.yaml
        - k8s/postgresql-service.yaml
        - k8s/postgresql-deployment.yaml
    deploy:
      kubeContext: orbstack
      kubectl: {}
    test:
      - image: amacneil/dbmate:2.28.0
        custom:
          - command: "sh -c 'apk add --no-cache postgresql-client && /scripts/test_migration.sh'"
            timeoutSeconds: 600
            dependencies:
              paths:
                - 'db/migrations/*.sql'
                - 'scripts/test_migration.sh'
