apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: r4c-cesium-viewer
build:
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
  artifacts:
    - image: r4c-cesium-viewer
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: r4c
        chartPath: helm
        valuesFiles:
          - helm/values.yaml
        setValueTemplates:
          r4c-cesium-viewer.image.repository: "{{.IMAGE_REPO_r4c-cesium-viewer}}"
          r4c-cesium-viewer.image.tag: "{{.IMAGE_TAG_r4c-cesium-viewer}}@{{.IMAGE_DIGEST_r4c-cesium-viewer}}"
        setValues:
          vite:
            digitransit_key: "placeholder"
            password_250: "placeholder"
          sentry:
            dsn: "placeholder"
            auth_token: "placeholder"
