apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: r4c-cesium-viewer
build:
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
  artifacts:
    - image: frontend
      context: .
      docker:
        dockerfile: Dockerfile
    - image: backend
      context: backend
      docker:
        dockerfile: Dockerfile
        buildArgs:
          VITE_BACKEND_URL: "http://r4c-cesium-viewer-backend/"
deploy:
  helm:
    releases:
      - name: r4c-cesium-viewer
        chartPath: helm
        valuesFiles:
          - helm/values.yaml
        setValueTemplates:
          frontend.image.repository: "{{.IMAGE_REPO_frontend}}"
          frontend.image.tag: "{{.IMAGE_TAG_frontend}}@{{.IMAGE_DIGEST_frontend}}"
          backend.image.repository: "{{.IMAGE_REPO_backend}}"
          backend.image.tag: "{{.IMAGE_TAG_backend}}@{{.IMAGE_DIGEST_backend}}"
        # setValues:
        #   frontend.image.pullPolicy: "IfNotPresent"
        #   backend.image.pullPolicy: "IfNotPresent"
