apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: r4c-cesium-viewer
build:
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
  artifacts:
    - image: frontend
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: r4c
        chartPath: helm
        valuesFiles:
          - helm/values.yaml
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_frontend}}"
          image.tag: "{{.IMAGE_TAG_frontend}}@{{.IMAGE_DIGEST_frontend}}"
        setValues:
          vite:
            digitransit_key: "placeholder"
            password_250: "placeholder"
          sentry:
            dsn: "placeholder"
            auth_token: "placeholder"
