apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: r4c-cesium-viewer
build:
  local:
    push: false
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
  artifacts:
    - image: frontend
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/serviceaccount.yaml
      - k8s/configmap.yaml
      - k8s/secrets.yaml
      - k8s/deployment.yaml
      - k8s/service.yaml
      - k8s/ingress.yaml
profiles:
  - name: local-with-services
    deploy:
      kubectl:
        manifests:
          - k8s/serviceaccount.yaml
          - k8s/configmap.yaml
          - k8s/secrets.yaml
          - k8s/migration-secret.yaml
          - k8s/migration-job.yaml
          - k8s/deployment.yaml
          - k8s/service.yaml
          - k8s/ingress.yaml
          - k8s/pygeoapi-deployment.yaml
      helm:
        releases:
          # PostgreSQL with PostGIS
          - name: postgresql
            remoteChart: postgresql
            repo: https://charts.bitnami.com/bitnami
            version: "16.7.14"
            namespace: default
            valuesFiles:
              - k8s/postgresql-values.yaml

  - name: migration-test
    deploy:
      helm:
        releases:
          # PostgreSQL with PostGIS for testing
          - name: postgresql
            remoteChart: postgresql
            repo: https://charts.bitnami.com/bitnami
            version: "16.7.14"
            namespace: default
            valuesFiles:
              - k8s/postgresql-values.yaml
    test:
      - image: amacneil/dbmate:v2.13.0
        custom:
          - command: "sh -c 'apk add --no-cache postgresql-client && /scripts/test_migration.sh'"
            timeoutSeconds: 600
            dependencies:
              paths:
                - "db/migrations/*.sql"
                - "scripts/test_migration.sh"
