apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: r4c-cesium-viewer
build:
  local:
    push: false
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
  artifacts:
    - image: frontend
      context: .
      docker:
        dockerfile: Dockerfile
      hooks:
        before:
          - command: ['sh', '-c', 'dotenvx run -- sh scripts/generate-secrets.sh']
            os: [darwin, linux]
manifests:
  rawYaml:
    - k8s/serviceaccount.yaml
    - k8s/configmap.yaml
    - k8s/deployment.yaml
    - k8s/service.yaml
    - k8s/ingress.yaml
deploy:
  kubectl:
    hooks:
      after:
        - host:
            command: ['sh', '-c', 'kubectl apply -f k8s/secrets.yaml']
            os: [darwin, linux]
profiles:
  - name: local-with-services
    manifests:
      rawYaml:
        - k8s/namespace.yaml
        - k8s/serviceaccount.yaml
        - k8s/configmap.yaml
        - k8s/migration-job.yaml
        - k8s/deployment.yaml
        - k8s/service.yaml
        - k8s/ingress.yaml
        - k8s/pygeoapi-deployment.yaml
        # PostgreSQL with PostGIS (official postgis/postgis image)
        - k8s/postgresql-secret.yaml
        - k8s/postgresql-configmap.yaml
        - k8s/postgresql-headless-service.yaml
        - k8s/postgresql-service.yaml
        - k8s/postgresql-statefulset.yaml
    deploy:
      kubectl:
        hooks:
          after:
            - host:
                command:
                  ['sh', '-c', 'kubectl apply -f k8s/secrets.yaml -f k8s/migration-secret.yaml']
                os: [darwin, linux]

  - name: migration-test
    manifests:
      rawYaml:
        - k8s/namespace.yaml
        # PostgreSQL with PostGIS (official postgis/postgis image)
        - k8s/postgresql-secret.yaml
        - k8s/postgresql-configmap.yaml
        - k8s/postgresql-headless-service.yaml
        - k8s/postgresql-service.yaml
        - k8s/postgresql-statefulset.yaml
    deploy:
      kubectl:
        hooks:
          after:
            - host:
                command: ['sh', '-c', 'kubectl apply -f k8s/migration-secret.yaml']
                os: [darwin, linux]
    test:
      - image: amacneil/dbmate:2.28.0
        custom:
          - command: "sh -c 'apk add --no-cache postgresql-client && /scripts/test_migration.sh'"
            timeoutSeconds: 600
            dependencies:
              paths:
                - 'db/migrations/*.sql'
                - 'scripts/test_migration.sh'
