apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: r4c-cesium-viewer
build:
  local:
    push: false
    useDockerCLI: true
    useBuildkit: true
    concurrency: 0
  artifacts:
    - image: frontend
      context: .
      docker:
        dockerfile: Dockerfile
        # Reuse layers from previous builds for faster rebuilds
        cacheFrom:
          - frontend:latest
      # Sync source files to container without full rebuild during dev
      sync:
        manual:
          - src: 'src/**/*.vue'
            dest: /app/src
          - src: 'src/**/*.js'
            dest: /app/src
          - src: 'src/**/*.css'
            dest: /app/src
      hooks:
        before:
          - command: ['sh', '-c', 'dotenvx run -- sh scripts/generate-secrets.sh']
            os: [darwin, linux]
          # Run lint before build to catch errors early
          - command: ['sh', '-c', 'npm run lint --silent || echo "Lint warnings found"']
            os: [darwin, linux]
manifests:
  rawYaml:
    - k8s/serviceaccount.yaml
    - k8s/configmap.yaml
    - k8s/deployment.yaml
    - k8s/service.yaml
    - k8s/ingress.yaml
deploy:
  kubectl:
    hooks:
      after:
        - host:
            command: ['sh', '-c', 'kubectl apply -f k8s/secrets.yaml']
            os: [darwin, linux]
  # Wait up to 180s for pods to be ready; tolerate init container restarts
  statusCheck: true
  statusCheckDeadlineSeconds: 180
  tolerateFailuresUntilDeadline: true
# Bind to localhost only for security
portForward:
  - resourceType: service
    resourceName: r4c-cesium-viewer
    port: 80
    localPort: 4173
    address: 127.0.0.1
profiles:
  - name: local-with-services
    manifests:
      rawYaml:
        - k8s/namespace.yaml
        - k8s/serviceaccount.yaml
        - k8s/configmap.yaml
        - k8s/migration-job.yaml
        - k8s/deployment.yaml
        - k8s/service.yaml
        - k8s/ingress.yaml
        - k8s/pygeoapi-deployment.yaml
        # PostgreSQL with PostGIS (official postgis/postgis image)
        - k8s/postgresql-secret.yaml
        - k8s/postgresql-configmap.yaml
        - k8s/postgresql-headless-service.yaml
        - k8s/postgresql-service.yaml
        - k8s/postgresql-statefulset.yaml
    deploy:
      kubectl:
        hooks:
          after:
            - host:
                command:
                  ['sh', '-c', 'kubectl apply -f k8s/secrets.yaml -f k8s/migration-secret.yaml']
                os: [darwin, linux]

  - name: migration-test
    manifests:
      rawYaml:
        - k8s/namespace.yaml
        # PostgreSQL with PostGIS (official postgis/postgis image)
        - k8s/postgresql-secret.yaml
        - k8s/postgresql-configmap.yaml
        - k8s/postgresql-headless-service.yaml
        - k8s/postgresql-service.yaml
        - k8s/postgresql-statefulset.yaml
    deploy:
      kubectl:
        hooks:
          after:
            - host:
                command: ['sh', '-c', 'kubectl apply -f k8s/migration-secret.yaml']
                os: [darwin, linux]
    test:
      - image: amacneil/dbmate:2.28.0
        custom:
          - command: "sh -c 'apk add --no-cache postgresql-client && /scripts/test_migration.sh'"
            timeoutSeconds: 600
            dependencies:
              paths:
                - 'db/migrations/*.sql'
                - 'scripts/test_migration.sh'
