apiVersion: v1
kind: Service
metadata:
  name: {{ include "r4c-cesium-viewer.frontend.fullname" . }}
  labels:
    {{- include "r4c-cesium-viewer.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "r4c-cesium-viewer.frontend.selectorLabels" . | nindent 6 }}
