{{- if .Values.migration.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-r4c.fullname" . }}-migration-secret
  labels:
    {{- include "helm-r4c.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  password: {{ .Values.migration.database.password | b64enc }}
  postgres-password: {{ .Values.migration.database.postgresPassword | b64enc }}
{{- end }}
