apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "r4c-cesium-viewer.pygeoapi.fullname" . }}-config
  labels:
    {{- include "r4c-cesium-viewer.pygeoapi.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- $config := deepCopy .Values.pygeoapi.config -}}
    {{- $postgresqlValues := index .Values "postgresql" -}}
    {{- range $resourceName, $resource := $config.resources -}}
      {{- range $providerIndex, $provider := $resource.providers -}}
        {{- if eq $provider.name "PostgreSQL" -}}
          {{- $_ := set $provider "data" (dict 
              "host" (printf "postgresql.default.svc.cluster.local" )
              "dbname" $postgresqlValues.auth.database
              "user" $postgresqlValues.auth.username
              "password" $postgresqlValues.auth.password
              "search_path" $provider.data.search_path
          ) -}}
        {{- end -}}
      {{- end -}}
    {{- end -}}
    {{ $config | toYaml | nindent 4 }}
