{{- if not .Values.secrets.existing_secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  {{- with .Values.secrets }}
  VITE_DIGITRANSIT_KEY: {{ .vite.digitransit_key | b64enc }}
  VITE_250_PASSWORD: {{ .vite.password_250 | b64enc }}
  SENTRY_AUTH_TOKEN: {{ .sentry.auth_token | b64enc }}
  SENTRY_DSN: {{ .sentry.dsn | b64enc }}
  {{- end }}
{{- end }}
