apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  VITE_DIGITRANSIT_KEY: {{ .Values.vite.digitransit_key | b64enc }}
  VITE_250_PASSWORD: {{ .Values.vite.password_250 | b64enc }}
  SENTRY_AUTH_TOKEN: {{ .Values.sentry.auth_token | b64enc }}
  SENTRY_DSN: {{ .Values.sentry.dsn | b64enc }}
