# PostgreSQL configuration for local development with PostGIS

auth:
  postgresPassword: "postgres"
  username: "regions4climate_user"
  password: "regions4climate_pass"
  database: "regions4climate"

primary:
  initdb:
    scripts:
      01-create-extensions.sql: |
        -- Create PostGIS extensions in the main regions4climate database
        -- Note: These will be created with superuser privileges during initdb
        CREATE EXTENSION IF NOT EXISTS postgis;
        CREATE EXTENSION IF NOT EXISTS postgis_topology;

        -- Verify PostGIS is working
        SELECT PostGIS_version();
      02-create-med-iren-db.sql: |
        -- Create secondary database for med_iren project
        CREATE DATABASE med_iren;
        \c med_iren;
        CREATE EXTENSION IF NOT EXISTS postgis;
        CREATE EXTENSION IF NOT EXISTS postgis_topology;

        -- Verify PostGIS is working in med_iren
        SELECT PostGIS_version();
      99-database-ready-marker.sh: |
        #!/bin/bash
        set -e
        echo "🎉 PostgreSQL initialization completed"
        echo "📋 Database: regions4climate"
        echo "📋 Extensions: PostGIS, PostGIS Topology"
        echo "📋 Ready for migrations via dbmate"

# Resource limits for local development
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Persistence settings for local development
persistence:
  enabled: true
  size: 2Gi

# Service configuration
service:
  type: ClusterIP
  ports:
    postgresql: 5432
