// src/constants/viewport.js
export const VIEWPORT = {
    MAX_CAMERA_HEIGHT_FOR_BUILDINGS: 50000,  // meters
    MAX_CAMERA_HEIGHT_FOR_TREES: 30000,      // meters
    DRAG_DETECTION_THRESHOLD_PX: 5,
    CLICK_PICK_TOLERANCE_PX: 5,
    MIN_ZOOM_FOR_DETAILS: 15
  }