/**
 * @module constants/vttFloodClassBreaks
 * GENERATED by scripts/vtt-flood/derive-class-breaks.mjs on 2026-10-08. Do not edit.
 * Regenerate: bun scripts/vtt-flood/derive-class-breaks.mjs
 *
 * Colour-class breaks per data source, scenario and dimension, fixed so the
 * classes do not change while scrubbing frames. Each entry pools the shown
 * values of 25 frames (every 12th from 0 to 276, plus 287)
 * and splits them into up to 8 equal-count classes
 * (scripts/vtt-flood/equalCountBreaks.mjs).
 * VTT data: upstream Last-Modified 2026-04-02T10:44:06Z to 2026-04-02T12:30:14Z (75 files).
 */

export interface VttClassBreaks {
	/** Strictly increasing class lower bounds. */
	readonly breaks: readonly number[]
	/** Upper end of the last class. */
	readonly upper: number
}

export type VttClassBreaksSource = 'vtt' | 'synthetic'

/** Parameters the breaks were derived with; a test checks they still match the constants. */
export const VTT_CLASS_BREAKS_DERIVATION = {
	steps: 8,
	frames: [
		0, 12, 24, 36, 48, 60, 72, 84, 96, 108, 120, 132, 144, 156, 168, 180, 192, 204, 216, 228, 240,
		252, 264, 276, 287,
	],
	quantiles: {
		transpiration: {
			lowerQuantile: 0.02,
			upperQuantile: 0.98,
		},
		upper_storage_water_depth: {
			lowerQuantile: 0.02,
			upperQuantile: 0.98,
		},
		canopy_air_temperature: {
			lowerQuantile: 0.02,
			upperQuantile: 0.98,
		},
	},
} as const

export const VTT_CLASS_BREAKS: Readonly<
	Record<VttClassBreaksSource, Readonly<Record<string, Readonly<Record<string, VttClassBreaks>>>>>
> = {
	vtt: {
		'1': {
			transpiration: {
				breaks: [
					0.003800000064074993, 0.01720000058412552, 0.029200000688433647, 0.042100001126527786,
					0.058400001376867294, 0.07660000026226044, 0.09880000352859497, 0.12960000336170197,
				],
				upper: 0.15530000627040863,
			},
			upper_storage_water_depth: {
				breaks: [0.0008999999845400453, 0.0010000000474974513],
				upper: 0.0010000000474974513,
			},
			canopy_air_temperature: {
				breaks: [5],
				upper: 5,
			},
		},
		'2': {
			transpiration: {
				breaks: [
					0.035999998450279236, 0.10090000182390213, 0.20229999721050262, 0.30480000376701355,
					0.4675000011920929, 0.6373999714851379, 0.8661999702453613, 1.1054999828338623,
				],
				upper: 1.3372999429702759,
			},
			upper_storage_water_depth: {
				breaks: [
					0.00039999998989515007, 0.0005000000237487257, 0.0006000000284984708,
					0.000699999975040555, 0.0007999999797903001, 0.0008999999845400453, 0.0010000000474974513,
				],
				upper: 0.0010000000474974513,
			},
			canopy_air_temperature: {
				breaks: [5],
				upper: 5,
			},
		},
		'3': {
			transpiration: {
				breaks: [
					0.031700000166893005, 0.29280000925064087, 0.44589999318122864, 0.5871000289916992,
					0.6945500075817108, 0.9991999864578247, 1.051300048828125, 1.6140999794006348,
				],
				upper: 1.8234620308876033,
			},
			upper_storage_water_depth: {
				breaks: [
					0.0003000000142492354, 0.00039999998989515007, 0.000699999975040555,
					0.0007999999797903001, 0.0010000000474974513,
				],
				upper: 0.0010000000474974513,
			},
			canopy_air_temperature: {
				breaks: [5],
				upper: 5,
			},
		},
	},
	synthetic: {
		'1': {
			transpiration: {
				breaks: [
					0.03392405577003956, 0.08764924854040146, 0.1128944680094719, 0.1402355283498764,
					0.1627732515335083, 0.1849438333511353, 0.2208428531885147, 0.2489108145236969,
				],
				upper: 0.2758019268512726,
			},
			upper_storage_water_depth: {
				breaks: [
					0.005220023430883885, 0.014374024234712124, 0.017154036089777946, 0.020130136981606483,
					0.02268626168370247, 0.025042055174708366, 0.02858986333012581, 0.031474120914936066,
				],
				upper: 0.03433425351977348,
			},
			canopy_air_temperature: {
				breaks: [
					292.0625793457031, 292.42848815917966, 292.8236981201172, 293.21183410644534,
					293.51075744628906, 293.7888311767578, 294.1556701660156, 294.4434509277344,
				],
				upper: 294.7769470214844,
			},
		},
		'2': {
			transpiration: {
				breaks: [
					0.06447068572044373, 0.0888019235432148, 0.1093439906835556, 0.13286881506443024,
					0.15185703337192535, 0.17499689638614654, 0.20214467495679855, 0.22632329255342482,
				],
				upper: 0.2591029691696167,
			},
			upper_storage_water_depth: {
				breaks: [
					0.005000576805323362, 0.005678669614717365, 0.0074248960893601185, 0.009477977026253939,
					0.011238595005124807, 0.013256777618080378, 0.015667019970715047, 0.01866705622524023,
				],
				upper: 0.02360346183180809,
			},
			canopy_air_temperature: {
				breaks: [
					292.7677947998047, 293.4305078125, 293.82453857421876, 294.07159912109375,
					294.27772521972656, 294.48017944335936, 294.6741027832031, 294.87565246582034,
				],
				upper: 295.1686724853516,
			},
		},
		'3': {
			transpiration: {
				breaks: [
					0.06152789980173111, 0.08500421032309532, 0.10578375175595284, 0.12746188670396805,
					0.14642500132322311, 0.16843128949403763, 0.19385305523872376, 0.21768350034952164,
				],
				upper: 0.2567498344182969,
			},
			upper_storage_water_depth: {
				breaks: [
					0.005000768657773733, 0.005898484494537115, 0.008149693477898836, 0.010622928068041802,
					0.012620436493307352, 0.014999474901705981, 0.017710874825716018, 0.021258597634732722,
				],
				upper: 0.026750510893762115,
			},
			canopy_air_temperature: {
				breaks: [
					292.31439086914065, 293.1307562255859, 293.6020947265625, 293.92103515625,
					294.1707763671875, 294.3921551513672, 294.6050372314453, 294.8184765625,
				],
				upper: 295.1576898193359,
			},
		},
	},
}
