#!/usr/bin/env bash
# SessionStart hook: install development tools when running in Claude Code on the web.
# Idempotent: each tool is skipped if already on PATH.
# Generated by /configure-plugin:configure-web-session.
set -euo pipefail

if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  echo "[install_pkgs] Not a remote environment, skipping."
  exit 0
fi

INSTALL_DIR="${HOME}/.local/bin"
mkdir -p "$INSTALL_DIR"
export PATH="$INSTALL_DIR:$PATH"

has() { command -v "$1" >/dev/null 2>&1; }

# --- pre-commit (via pip) ---
if ! has pre-commit; then
  echo "[install_pkgs] Installing pre-commit..."
  pip install --user --quiet pre-commit
else
  echo "[install_pkgs] pre-commit already installed, skipping."
fi

# --- just 1.40.0 ---
JUST_VERSION="1.40.0"
if ! has just; then
  echo "[install_pkgs] Installing just ${JUST_VERSION}..."
  tmpdir=$(mktemp -d)
  curl -fsSL "https://github.com/casey/just/releases/download/${JUST_VERSION}/just-${JUST_VERSION}-x86_64-unknown-linux-musl.tar.gz" | tar xz -C "${tmpdir}" just
  mv "${tmpdir}/just" "${INSTALL_DIR}/just"
  chmod +x "${INSTALL_DIR}/just"
  rm -rf "${tmpdir}"
else
  echo "[install_pkgs] just already installed, skipping."
fi

# --- Summary ---
echo "[install_pkgs] Done. Available tools:"
for cmd in pre-commit just ; do
  if has "$cmd"; then
    echo "  $cmd: $(command -v "$cmd")"
  else
    echo "  $cmd: NOT FOUND (install failed)"
  fi
done
