apiVersion: v2
name: r4c-cesium-viewer
description: A Helm chart for Kubernetes
type: application
version: 0.2.0

dependencies:
  - name: redis
    version: 20.1.5
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: 15.5.36
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
