# Local development overrides with migrations enabled
# Use with: skaffold dev --profile=local-with-services -f helm/values-local-with-migrations.yaml

# Include all local development settings
# This file should be used in addition to values-local.yaml

# Enable database migrations for local development
migration:
  enabled: true
  database:
    host: postgresql
    port: 5432
    name: regions4climate
    username: regions4climate_user
    password: regions4climate_pass
    postgresPassword: postgres
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
