name: Auto-merge image updater PRs

on:
  push:
    branches:
      - 'image-updater-**'

jobs:
  auto-merge:
    uses: ForumViriumHelsinki/.github/.github/workflows/reusable-auto-merge-image-updater.yml@main
    secrets:
      AUTO_MERGE_PAT: ${{ secrets.AUTO_MERGE_PAT }}
