apiVersion: v1
kind: Secret
metadata:
  name: r4c-cesium-viewer-migration-secret
  labels:
    app.kubernetes.io/name: r4c-cesium-viewer
    app.kubernetes.io/instance: r4c-cesium-viewer
    app.kubernetes.io/component: migration
type: Opaque
stringData:
  # Default values for local development
  password: "regions4climate_pass"
  admin-password: "postgres"
