apiVersion: v1
kind: Secret
metadata:
  name: r4c-cesium-viewer-secrets
type: Opaque
stringData:
  # These values will be overridden by Skaffold setValueTemplates
  VITE_DIGITRANSIT_KEY: ""
  SENTRY_AUTH_TOKEN: ""
  SENTRY_DSN: ""
